In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,78,9])

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6, 78,  9])

In [4]:
reshaped = arr.reshape(4,2)

In [5]:
reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [78,  9]])

In [6]:
flattened = reshaped.flatten()

In [7]:
flattened

array([ 1,  2,  3,  4,  5,  6, 78,  9])

In [8]:
flattened[0] = 99

In [9]:
flattened

array([99,  2,  3,  4,  5,  6, 78,  9])

In [10]:
reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [78,  9]])

In [11]:
reveled = reshaped.ravel()
reveled[1] = 88
reveled

array([ 1, 88,  3,  4,  5,  6, 78,  9])

In [12]:
reshaped

array([[ 1, 88],
       [ 3,  4],
       [ 5,  6],
       [78,  9]])

In [13]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([2,3,4])
print(arr2)

[1 2 3]
[2 3 4]


In [14]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([[2],[3],[4]])
print(arr2)

[1 2 3]
[[2]
 [3]
 [4]]


In [15]:
arr1 + arr2

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [16]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([2,3,4])
print(arr2)
arr1 + arr2

[1 2 3]
[2 3 4]


array([3, 5, 7])

In [17]:
arr1 = np.array([1,2,3])
print(arr1.ndim)
arr2 = np.array([2,3,4])
print(arr2.ndim)
arr1 + arr2

1
1


array([3, 5, 7])